kafka:
  bootstrap_servers: 'localhost:39092'
  topic: 'amazon_reviews'
  group_id: 'review_detector'
  auto_offset_reset: 'earliest'
  enable_auto_commit: true
  max_poll_interval_ms: 300000

model:
  input_features: 5000
  hidden_layers: [512, 256, 128, 64]
  dropout_rates: [0.2, 0.2, 0.2, 0.1]
  learning_rate: 0.0005
  batch_size: 32
  epochs: 100
  early_stopping_patience: 10
  use_batch_normalization: true
  use_class_weights: true 